[package]
name = "queue-client"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config    = { workspace = true }
aws-sdk-sqs   = { workspace = true }
tokio         = { workspace = true }
serde         = { workspace = true, features = ["derive"] }
serde_json    = { workspace = true }
thiserror     = { workspace = true }
domain        = { workspace = true }