[package]
name = "parsing-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
scraper        = { workspace = true }
url            = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
tokio          = { workspace = true }
config         = { workspace = true }
domain         = { workspace = true }
queue-client   = { workspace = true }
storage-client = { workspace = true }
